version: "3"
services:
  mysql:
    image: mysql:8.0.19
    container_name: mysql
    entrypoint: [ 'docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password' ]
    environment:
      MYSQL_DATABASE: neoris
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql #hot reloading
#  neoris:
#    build: .
#    image: neoris
#    ports:
#      - "8081:8080"
#    links:
#      - mysql